// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: attestation.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Metadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        map[string]string      `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_attestation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_attestation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_attestation_proto_rawDescGZIP(), []int{0}
}

func (x *Metadata) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

type Timestamp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seconds       int64                  `protobuf:"varint,1,opt,name=seconds,proto3" json:"seconds,omitempty"`
	Nanos         int32                  `protobuf:"varint,2,opt,name=nanos,proto3" json:"nanos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Timestamp) Reset() {
	*x = Timestamp{}
	mi := &file_attestation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Timestamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Timestamp) ProtoMessage() {}

func (x *Timestamp) ProtoReflect() protoreflect.Message {
	mi := &file_attestation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Timestamp.ProtoReflect.Descriptor instead.
func (*Timestamp) Descriptor() ([]byte, []int) {
	return file_attestation_proto_rawDescGZIP(), []int{1}
}

func (x *Timestamp) GetSeconds() int64 {
	if x != nil {
		return x.Seconds
	}
	return 0
}

func (x *Timestamp) GetNanos() int32 {
	if x != nil {
		return x.Nanos
	}
	return 0
}

type EventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	EventType     string                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	DocumentHash  string                 `protobuf:"bytes,4,opt,name=document_hash,json=documentHash,proto3" json:"document_hash,omitempty"`
	Metadata      *Metadata              `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Timestamp     *Timestamp             `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Signature     string                 `protobuf:"bytes,7,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventRequest) Reset() {
	*x = EventRequest{}
	mi := &file_attestation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventRequest) ProtoMessage() {}

func (x *EventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_attestation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventRequest.ProtoReflect.Descriptor instead.
func (*EventRequest) Descriptor() ([]byte, []int) {
	return file_attestation_proto_rawDescGZIP(), []int{2}
}

func (x *EventRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *EventRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *EventRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *EventRequest) GetDocumentHash() string {
	if x != nil {
		return x.DocumentHash
	}
	return ""
}

func (x *EventRequest) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *EventRequest) GetTimestamp() *Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *EventRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type EventResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	EventId               string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	CertificateId         string                 `protobuf:"bytes,2,opt,name=certificate_id,json=certificateId,proto3" json:"certificate_id,omitempty"`
	IpfsHash              string                 `protobuf:"bytes,3,opt,name=ipfs_hash,json=ipfsHash,proto3" json:"ipfs_hash,omitempty"`
	Status                string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // queued, confirmed, settled
	MerkleRoot            string                 `protobuf:"bytes,5,opt,name=merkle_root,json=merkleRoot,proto3" json:"merkle_root,omitempty"`
	QueuePosition         int32                  `protobuf:"varint,6,opt,name=queue_position,json=queuePosition,proto3" json:"queue_position,omitempty"`
	EstimatedConfirmation string                 `protobuf:"bytes,7,opt,name=estimated_confirmation,json=estimatedConfirmation,proto3" json:"estimated_confirmation,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *EventResponse) Reset() {
	*x = EventResponse{}
	mi := &file_attestation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventResponse) ProtoMessage() {}

func (x *EventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_attestation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventResponse.ProtoReflect.Descriptor instead.
func (*EventResponse) Descriptor() ([]byte, []int) {
	return file_attestation_proto_rawDescGZIP(), []int{3}
}

func (x *EventResponse) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *EventResponse) GetCertificateId() string {
	if x != nil {
		return x.CertificateId
	}
	return ""
}

func (x *EventResponse) GetIpfsHash() string {
	if x != nil {
		return x.IpfsHash
	}
	return ""
}

func (x *EventResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *EventResponse) GetMerkleRoot() string {
	if x != nil {
		return x.MerkleRoot
	}
	return ""
}

func (x *EventResponse) GetQueuePosition() int32 {
	if x != nil {
		return x.QueuePosition
	}
	return 0
}

func (x *EventResponse) GetEstimatedConfirmation() string {
	if x != nil {
		return x.EstimatedConfirmation
	}
	return ""
}

type BatchEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Events        []*EventRequest        `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchEventRequest) Reset() {
	*x = BatchEventRequest{}
	mi := &file_attestation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchEventRequest) ProtoMessage() {}

func (x *BatchEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_attestation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchEventRequest.ProtoReflect.Descriptor instead.
func (*BatchEventRequest) Descriptor() ([]byte, []int) {
	return file_attestation_proto_rawDescGZIP(), []int{4}
}

func (x *BatchEventRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *BatchEventRequest) GetEvents() []*EventRequest {
	if x != nil {
		return x.Events
	}
	return nil
}

type BatchEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalEvents   int32                  `protobuf:"varint,1,opt,name=total_events,json=totalEvents,proto3" json:"total_events,omitempty"`
	Queued        int32                  `protobuf:"varint,2,opt,name=queued,proto3" json:"queued,omitempty"`
	Failed        int32                  `protobuf:"varint,3,opt,name=failed,proto3" json:"failed,omitempty"`
	Responses     []*EventResponse       `protobuf:"bytes,4,rep,name=responses,proto3" json:"responses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchEventResponse) Reset() {
	*x = BatchEventResponse{}
	mi := &file_attestation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchEventResponse) ProtoMessage() {}

func (x *BatchEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_attestation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchEventResponse.ProtoReflect.Descriptor instead.
func (*BatchEventResponse) Descriptor() ([]byte, []int) {
	return file_attestation_proto_rawDescGZIP(), []int{5}
}

func (x *BatchEventResponse) GetTotalEvents() int32 {
	if x != nil {
		return x.TotalEvents
	}
	return 0
}

func (x *BatchEventResponse) GetQueued() int32 {
	if x != nil {
		return x.Queued
	}
	return 0
}

func (x *BatchEventResponse) GetFailed() int32 {
	if x != nil {
		return x.Failed
	}
	return 0
}

func (x *BatchEventResponse) GetResponses() []*EventResponse {
	if x != nil {
		return x.Responses
	}
	return nil
}

type EventStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventStatusRequest) Reset() {
	*x = EventStatusRequest{}
	mi := &file_attestation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventStatusRequest) ProtoMessage() {}

func (x *EventStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_attestation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventStatusRequest.ProtoReflect.Descriptor instead.
func (*EventStatusRequest) Descriptor() ([]byte, []int) {
	return file_attestation_proto_rawDescGZIP(), []int{6}
}

func (x *EventStatusRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *EventStatusRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type EventStatusResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	EventId          string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Status           string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	IpfsHash         string                 `protobuf:"bytes,3,opt,name=ipfs_hash,json=ipfsHash,proto3" json:"ipfs_hash,omitempty"`
	BlockchainTxHash string                 `protobuf:"bytes,4,opt,name=blockchain_tx_hash,json=blockchainTxHash,proto3" json:"blockchain_tx_hash,omitempty"`
	BlockchainBlock  int64                  `protobuf:"varint,5,opt,name=blockchain_block,json=blockchainBlock,proto3" json:"blockchain_block,omitempty"`
	BatchId          string                 `protobuf:"bytes,6,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	MerkleRoot       string                 `protobuf:"bytes,7,opt,name=merkle_root,json=merkleRoot,proto3" json:"merkle_root,omitempty"`
	MerkleProof      []string               `protobuf:"bytes,8,rep,name=merkle_proof,json=merkleProof,proto3" json:"merkle_proof,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EventStatusResponse) Reset() {
	*x = EventStatusResponse{}
	mi := &file_attestation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventStatusResponse) ProtoMessage() {}

func (x *EventStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_attestation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventStatusResponse.ProtoReflect.Descriptor instead.
func (*EventStatusResponse) Descriptor() ([]byte, []int) {
	return file_attestation_proto_rawDescGZIP(), []int{7}
}

func (x *EventStatusResponse) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *EventStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *EventStatusResponse) GetIpfsHash() string {
	if x != nil {
		return x.IpfsHash
	}
	return ""
}

func (x *EventStatusResponse) GetBlockchainTxHash() string {
	if x != nil {
		return x.BlockchainTxHash
	}
	return ""
}

func (x *EventStatusResponse) GetBlockchainBlock() int64 {
	if x != nil {
		return x.BlockchainBlock
	}
	return 0
}

func (x *EventStatusResponse) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *EventStatusResponse) GetMerkleRoot() string {
	if x != nil {
		return x.MerkleRoot
	}
	return ""
}

func (x *EventStatusResponse) GetMerkleProof() []string {
	if x != nil {
		return x.MerkleProof
	}
	return nil
}

type ForceBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForceBatchRequest) Reset() {
	*x = ForceBatchRequest{}
	mi := &file_attestation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForceBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForceBatchRequest) ProtoMessage() {}

func (x *ForceBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_attestation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForceBatchRequest.ProtoReflect.Descriptor instead.
func (*ForceBatchRequest) Descriptor() ([]byte, []int) {
	return file_attestation_proto_rawDescGZIP(), []int{8}
}

func (x *ForceBatchRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type ForceBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Triggered     bool                   `protobuf:"varint,1,opt,name=triggered,proto3" json:"triggered,omitempty"`
	QueueLength   int32                  `protobuf:"varint,2,opt,name=queue_length,json=queueLength,proto3" json:"queue_length,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForceBatchResponse) Reset() {
	*x = ForceBatchResponse{}
	mi := &file_attestation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForceBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForceBatchResponse) ProtoMessage() {}

func (x *ForceBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_attestation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForceBatchResponse.ProtoReflect.Descriptor instead.
func (*ForceBatchResponse) Descriptor() ([]byte, []int) {
	return file_attestation_proto_rawDescGZIP(), []int{9}
}

func (x *ForceBatchResponse) GetTriggered() bool {
	if x != nil {
		return x.Triggered
	}
	return false
}

func (x *ForceBatchResponse) GetQueueLength() int32 {
	if x != nil {
		return x.QueueLength
	}
	return 0
}

func (x *ForceBatchResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CreateChannelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ChannelType   string                 `protobuf:"bytes,3,opt,name=channel_type,json=channelType,proto3" json:"channel_type,omitempty"` // custodial, non_custodial
	Config        *ChannelConfig         `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChannelRequest) Reset() {
	*x = CreateChannelRequest{}
	mi := &file_attestation_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChannelRequest) ProtoMessage() {}

func (x *CreateChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_attestation_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChannelRequest.ProtoReflect.Descriptor instead.
func (*CreateChannelRequest) Descriptor() ([]byte, []int) {
	return file_attestation_proto_rawDescGZIP(), []int{10}
}

func (x *CreateChannelRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreateChannelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateChannelRequest) GetChannelType() string {
	if x != nil {
		return x.ChannelType
	}
	return ""
}

func (x *CreateChannelRequest) GetConfig() *ChannelConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type ChannelConfig struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	SettlementIntervalSeconds int32                  `protobuf:"varint,1,opt,name=settlement_interval_seconds,json=settlementIntervalSeconds,proto3" json:"settlement_interval_seconds,omitempty"`
	MaxEventsBeforeSettle     int32                  `protobuf:"varint,2,opt,name=max_events_before_settle,json=maxEventsBeforeSettle,proto3" json:"max_events_before_settle,omitempty"`
	AutoSettle                bool                   `protobuf:"varint,3,opt,name=auto_settle,json=autoSettle,proto3" json:"auto_settle,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *ChannelConfig) Reset() {
	*x = ChannelConfig{}
	mi := &file_attestation_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelConfig) ProtoMessage() {}

func (x *ChannelConfig) ProtoReflect() protoreflect.Message {
	mi := &file_attestation_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelConfig.ProtoReflect.Descriptor instead.
func (*ChannelConfig) Descriptor() ([]byte, []int) {
	return file_attestation_proto_rawDescGZIP(), []int{11}
}

func (x *ChannelConfig) GetSettlementIntervalSeconds() int32 {
	if x != nil {
		return x.SettlementIntervalSeconds
	}
	return 0
}

func (x *ChannelConfig) GetMaxEventsBeforeSettle() int32 {
	if x != nil {
		return x.MaxEventsBeforeSettle
	}
	return 0
}

func (x *ChannelConfig) GetAutoSettle() bool {
	if x != nil {
		return x.AutoSettle
	}
	return false
}

type ChannelResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ChannelId           string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	TenantId            string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	State               string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"` // open, settling, closed
	CurrentSequence     int64                  `protobuf:"varint,4,opt,name=current_sequence,json=currentSequence,proto3" json:"current_sequence,omitempty"`
	TotalEvents         int64                  `protobuf:"varint,5,opt,name=total_events,json=totalEvents,proto3" json:"total_events,omitempty"`
	PendingEvents       int64                  `protobuf:"varint,6,opt,name=pending_events,json=pendingEvents,proto3" json:"pending_events,omitempty"`
	LastSettledSequence int64                  `protobuf:"varint,7,opt,name=last_settled_sequence,json=lastSettledSequence,proto3" json:"last_settled_sequence,omitempty"`
	CurrentMerkleRoot   string                 `protobuf:"bytes,8,opt,name=current_merkle_root,json=currentMerkleRoot,proto3" json:"current_merkle_root,omitempty"`
	SettlementCount     int32                  `protobuf:"varint,9,opt,name=settlement_count,json=settlementCount,proto3" json:"settlement_count,omitempty"`
	CreatedAt           *Timestamp             `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastSettlementTime  *Timestamp             `protobuf:"bytes,11,opt,name=last_settlement_time,json=lastSettlementTime,proto3" json:"last_settlement_time,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ChannelResponse) Reset() {
	*x = ChannelResponse{}
	mi := &file_attestation_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelResponse) ProtoMessage() {}

func (x *ChannelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_attestation_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelResponse.ProtoReflect.Descriptor instead.
func (*ChannelResponse) Descriptor() ([]byte, []int) {
	return file_attestation_proto_rawDescGZIP(), []int{12}
}

func (x *ChannelResponse) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *ChannelResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ChannelResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ChannelResponse) GetCurrentSequence() int64 {
	if x != nil {
		return x.CurrentSequence
	}
	return 0
}

func (x *ChannelResponse) GetTotalEvents() int64 {
	if x != nil {
		return x.TotalEvents
	}
	return 0
}

func (x *ChannelResponse) GetPendingEvents() int64 {
	if x != nil {
		return x.PendingEvents
	}
	return 0
}

func (x *ChannelResponse) GetLastSettledSequence() int64 {
	if x != nil {
		return x.LastSettledSequence
	}
	return 0
}

func (x *ChannelResponse) GetCurrentMerkleRoot() string {
	if x != nil {
		return x.CurrentMerkleRoot
	}
	return ""
}

func (x *ChannelResponse) GetSettlementCount() int32 {
	if x != nil {
		return x.SettlementCount
	}
	return 0
}

func (x *ChannelResponse) GetCreatedAt() *Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ChannelResponse) GetLastSettlementTime() *Timestamp {
	if x != nil {
		return x.LastSettlementTime
	}
	return nil
}

type ChannelEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	EventId       string                 `protobuf:"bytes,3,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventType     string                 `protobuf:"bytes,4,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	DataHash      string                 `protobuf:"bytes,5,opt,name=data_hash,json=dataHash,proto3" json:"data_hash,omitempty"`
	Metadata      *Metadata              `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Signature     string                 `protobuf:"bytes,7,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelEventRequest) Reset() {
	*x = ChannelEventRequest{}
	mi := &file_attestation_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelEventRequest) ProtoMessage() {}

func (x *ChannelEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_attestation_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelEventRequest.ProtoReflect.Descriptor instead.
func (*ChannelEventRequest) Descriptor() ([]byte, []int) {
	return file_attestation_proto_rawDescGZIP(), []int{13}
}

func (x *ChannelEventRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *ChannelEventRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ChannelEventRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *ChannelEventRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *ChannelEventRequest) GetDataHash() string {
	if x != nil {
		return x.DataHash
	}
	return ""
}

func (x *ChannelEventRequest) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ChannelEventRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type ChannelEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Sequence      int64                  `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	EventHash     string                 `protobuf:"bytes,3,opt,name=event_hash,json=eventHash,proto3" json:"event_hash,omitempty"`
	MerkleRoot    string                 `protobuf:"bytes,4,opt,name=merkle_root,json=merkleRoot,proto3" json:"merkle_root,omitempty"`
	ShouldSettle  bool                   `protobuf:"varint,5,opt,name=should_settle,json=shouldSettle,proto3" json:"should_settle,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelEventResponse) Reset() {
	*x = ChannelEventResponse{}
	mi := &file_attestation_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelEventResponse) ProtoMessage() {}

func (x *ChannelEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_attestation_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelEventResponse.ProtoReflect.Descriptor instead.
func (*ChannelEventResponse) Descriptor() ([]byte, []int) {
	return file_attestation_proto_rawDescGZIP(), []int{14}
}

func (x *ChannelEventResponse) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *ChannelEventResponse) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *ChannelEventResponse) GetEventHash() string {
	if x != nil {
		return x.EventHash
	}
	return ""
}

func (x *ChannelEventResponse) GetMerkleRoot() string {
	if x != nil {
		return x.MerkleRoot
	}
	return ""
}

func (x *ChannelEventResponse) GetShouldSettle() bool {
	if x != nil {
		return x.ShouldSettle
	}
	return false
}

func (x *ChannelEventResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ChannelStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelStatusRequest) Reset() {
	*x = ChannelStatusRequest{}
	mi := &file_attestation_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelStatusRequest) ProtoMessage() {}

func (x *ChannelStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_attestation_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelStatusRequest.ProtoReflect.Descriptor instead.
func (*ChannelStatusRequest) Descriptor() ([]byte, []int) {
	return file_attestation_proto_rawDescGZIP(), []int{15}
}

func (x *ChannelStatusRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *ChannelStatusRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type SettleChannelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettleChannelRequest) Reset() {
	*x = SettleChannelRequest{}
	mi := &file_attestation_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettleChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettleChannelRequest) ProtoMessage() {}

func (x *SettleChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_attestation_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettleChannelRequest.ProtoReflect.Descriptor instead.
func (*SettleChannelRequest) Descriptor() ([]byte, []int) {
	return file_attestation_proto_rawDescGZIP(), []int{16}
}

func (x *SettleChannelRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *SettleChannelRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type SettlementResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SettlementId  string                 `protobuf:"bytes,1,opt,name=settlement_id,json=settlementId,proto3" json:"settlement_id,omitempty"`
	ChannelId     string                 `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	MerkleRoot    string                 `protobuf:"bytes,3,opt,name=merkle_root,json=merkleRoot,proto3" json:"merkle_root,omitempty"`
	EventCount    int64                  `protobuf:"varint,4,opt,name=event_count,json=eventCount,proto3" json:"event_count,omitempty"`
	StartSequence int64                  `protobuf:"varint,5,opt,name=start_sequence,json=startSequence,proto3" json:"start_sequence,omitempty"`
	EndSequence   int64                  `protobuf:"varint,6,opt,name=end_sequence,json=endSequence,proto3" json:"end_sequence,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"` // pending, submitted, confirmed
	TxHash        string                 `protobuf:"bytes,8,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	BlockNumber   int64                  `protobuf:"varint,9,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettlementResponse) Reset() {
	*x = SettlementResponse{}
	mi := &file_attestation_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettlementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettlementResponse) ProtoMessage() {}

func (x *SettlementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_attestation_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettlementResponse.ProtoReflect.Descriptor instead.
func (*SettlementResponse) Descriptor() ([]byte, []int) {
	return file_attestation_proto_rawDescGZIP(), []int{17}
}

func (x *SettlementResponse) GetSettlementId() string {
	if x != nil {
		return x.SettlementId
	}
	return ""
}

func (x *SettlementResponse) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *SettlementResponse) GetMerkleRoot() string {
	if x != nil {
		return x.MerkleRoot
	}
	return ""
}

func (x *SettlementResponse) GetEventCount() int64 {
	if x != nil {
		return x.EventCount
	}
	return 0
}

func (x *SettlementResponse) GetStartSequence() int64 {
	if x != nil {
		return x.StartSequence
	}
	return 0
}

func (x *SettlementResponse) GetEndSequence() int64 {
	if x != nil {
		return x.EndSequence
	}
	return 0
}

func (x *SettlementResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SettlementResponse) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *SettlementResponse) GetBlockNumber() int64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

type CloseChannelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	SettleFirst   bool                   `protobuf:"varint,3,opt,name=settle_first,json=settleFirst,proto3" json:"settle_first,omitempty"` // Settle pending events before closing
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseChannelRequest) Reset() {
	*x = CloseChannelRequest{}
	mi := &file_attestation_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseChannelRequest) ProtoMessage() {}

func (x *CloseChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_attestation_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseChannelRequest.ProtoReflect.Descriptor instead.
func (*CloseChannelRequest) Descriptor() ([]byte, []int) {
	return file_attestation_proto_rawDescGZIP(), []int{18}
}

func (x *CloseChannelRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *CloseChannelRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CloseChannelRequest) GetSettleFirst() bool {
	if x != nil {
		return x.SettleFirst
	}
	return false
}

type EndpointsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"` // Optional - for tenant-specific routing
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndpointsRequest) Reset() {
	*x = EndpointsRequest{}
	mi := &file_attestation_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointsRequest) ProtoMessage() {}

func (x *EndpointsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_attestation_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointsRequest.ProtoReflect.Descriptor instead.
func (*EndpointsRequest) Descriptor() ([]byte, []int) {
	return file_attestation_proto_rawDescGZIP(), []int{19}
}

func (x *EndpointsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type EndpointsResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Endpoints              []*Endpoint            `protobuf:"bytes,1,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	RecommendedConnections int32                  `protobuf:"varint,2,opt,name=recommended_connections,json=recommendedConnections,proto3" json:"recommended_connections,omitempty"` // Suggested number of parallel connections
	TtlSeconds             int32                  `protobuf:"varint,3,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`                                     // How long to cache this response
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *EndpointsResponse) Reset() {
	*x = EndpointsResponse{}
	mi := &file_attestation_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointsResponse) ProtoMessage() {}

func (x *EndpointsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_attestation_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointsResponse.ProtoReflect.Descriptor instead.
func (*EndpointsResponse) Descriptor() ([]byte, []int) {
	return file_attestation_proto_rawDescGZIP(), []int{20}
}

func (x *EndpointsResponse) GetEndpoints() []*Endpoint {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *EndpointsResponse) GetRecommendedConnections() int32 {
	if x != nil {
		return x.RecommendedConnections
	}
	return 0
}

func (x *EndpointsResponse) GetTtlSeconds() int32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type Endpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"` // host:port
	UseTls        bool                   `protobuf:"varint,2,opt,name=use_tls,json=useTls,proto3" json:"use_tls,omitempty"`
	Weight        int32                  `protobuf:"varint,3,opt,name=weight,proto3" json:"weight,omitempty"`                              // For weighted load balancing (higher = more traffic)
	Region        string                 `protobuf:"bytes,4,opt,name=region,proto3" json:"region,omitempty"`                               // Optional region hint
	CurrentLoad   int32                  `protobuf:"varint,5,opt,name=current_load,json=currentLoad,proto3" json:"current_load,omitempty"` // 0-100 load percentage
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Endpoint) Reset() {
	*x = Endpoint{}
	mi := &file_attestation_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Endpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Endpoint) ProtoMessage() {}

func (x *Endpoint) ProtoReflect() protoreflect.Message {
	mi := &file_attestation_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Endpoint.ProtoReflect.Descriptor instead.
func (*Endpoint) Descriptor() ([]byte, []int) {
	return file_attestation_proto_rawDescGZIP(), []int{21}
}

func (x *Endpoint) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Endpoint) GetUseTls() bool {
	if x != nil {
		return x.UseTls
	}
	return false
}

func (x *Endpoint) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Endpoint) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Endpoint) GetCurrentLoad() int32 {
	if x != nil {
		return x.CurrentLoad
	}
	return 0
}

type ClusterInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterInfoRequest) Reset() {
	*x = ClusterInfoRequest{}
	mi := &file_attestation_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterInfoRequest) ProtoMessage() {}

func (x *ClusterInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_attestation_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterInfoRequest.ProtoReflect.Descriptor instead.
func (*ClusterInfoRequest) Descriptor() ([]byte, []int) {
	return file_attestation_proto_rawDescGZIP(), []int{22}
}

type ClusterInfoResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TotalNodes      int32                  `protobuf:"varint,1,opt,name=total_nodes,json=totalNodes,proto3" json:"total_nodes,omitempty"`
	HealthyNodes    int32                  `protobuf:"varint,2,opt,name=healthy_nodes,json=healthyNodes,proto3" json:"healthy_nodes,omitempty"`
	EventsPerSecond int64                  `protobuf:"varint,3,opt,name=events_per_second,json=eventsPerSecond,proto3" json:"events_per_second,omitempty"`
	QueueDepth      int64                  `protobuf:"varint,4,opt,name=queue_depth,json=queueDepth,proto3" json:"queue_depth,omitempty"`
	ClusterVersion  string                 `protobuf:"bytes,5,opt,name=cluster_version,json=clusterVersion,proto3" json:"cluster_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ClusterInfoResponse) Reset() {
	*x = ClusterInfoResponse{}
	mi := &file_attestation_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterInfoResponse) ProtoMessage() {}

func (x *ClusterInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_attestation_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterInfoResponse.ProtoReflect.Descriptor instead.
func (*ClusterInfoResponse) Descriptor() ([]byte, []int) {
	return file_attestation_proto_rawDescGZIP(), []int{23}
}

func (x *ClusterInfoResponse) GetTotalNodes() int32 {
	if x != nil {
		return x.TotalNodes
	}
	return 0
}

func (x *ClusterInfoResponse) GetHealthyNodes() int32 {
	if x != nil {
		return x.HealthyNodes
	}
	return 0
}

func (x *ClusterInfoResponse) GetEventsPerSecond() int64 {
	if x != nil {
		return x.EventsPerSecond
	}
	return 0
}

func (x *ClusterInfoResponse) GetQueueDepth() int64 {
	if x != nil {
		return x.QueueDepth
	}
	return 0
}

func (x *ClusterInfoResponse) GetClusterVersion() string {
	if x != nil {
		return x.ClusterVersion
	}
	return ""
}

var File_attestation_proto protoreflect.FileDescriptor

const file_attestation_proto_rawDesc = "" +
	"\n" +
	"\x11attestation.proto\x12\vattestation\"\x80\x01\n" +
	"\bMetadata\x129\n" +
	"\x06fields\x18\x01 \x03(\v2!.attestation.Metadata.FieldsEntryR\x06fields\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\";\n" +
	"\tTimestamp\x12\x18\n" +
	"\aseconds\x18\x01 \x01(\x03R\aseconds\x12\x14\n" +
	"\x05nanos\x18\x02 \x01(\x05R\x05nanos\"\x8f\x02\n" +
	"\fEventRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\x12#\n" +
	"\rdocument_hash\x18\x04 \x01(\tR\fdocumentHash\x121\n" +
	"\bmetadata\x18\x05 \x01(\v2\x15.attestation.MetadataR\bmetadata\x124\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x16.attestation.TimestampR\ttimestamp\x12\x1c\n" +
	"\tsignature\x18\a \x01(\tR\tsignature\"\x85\x02\n" +
	"\rEventResponse\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12%\n" +
	"\x0ecertificate_id\x18\x02 \x01(\tR\rcertificateId\x12\x1b\n" +
	"\tipfs_hash\x18\x03 \x01(\tR\bipfsHash\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1f\n" +
	"\vmerkle_root\x18\x05 \x01(\tR\n" +
	"merkleRoot\x12%\n" +
	"\x0equeue_position\x18\x06 \x01(\x05R\rqueuePosition\x125\n" +
	"\x16estimated_confirmation\x18\a \x01(\tR\x15estimatedConfirmation\"c\n" +
	"\x11BatchEventRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x121\n" +
	"\x06events\x18\x02 \x03(\v2\x19.attestation.EventRequestR\x06events\"\xa1\x01\n" +
	"\x12BatchEventResponse\x12!\n" +
	"\ftotal_events\x18\x01 \x01(\x05R\vtotalEvents\x12\x16\n" +
	"\x06queued\x18\x02 \x01(\x05R\x06queued\x12\x16\n" +
	"\x06failed\x18\x03 \x01(\x05R\x06failed\x128\n" +
	"\tresponses\x18\x04 \x03(\v2\x1a.attestation.EventResponseR\tresponses\"L\n" +
	"\x12EventStatusRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\"\x9d\x02\n" +
	"\x13EventStatusResponse\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1b\n" +
	"\tipfs_hash\x18\x03 \x01(\tR\bipfsHash\x12,\n" +
	"\x12blockchain_tx_hash\x18\x04 \x01(\tR\x10blockchainTxHash\x12)\n" +
	"\x10blockchain_block\x18\x05 \x01(\x03R\x0fblockchainBlock\x12\x19\n" +
	"\bbatch_id\x18\x06 \x01(\tR\abatchId\x12\x1f\n" +
	"\vmerkle_root\x18\a \x01(\tR\n" +
	"merkleRoot\x12!\n" +
	"\fmerkle_proof\x18\b \x03(\tR\vmerkleProof\"0\n" +
	"\x11ForceBatchRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\"o\n" +
	"\x12ForceBatchResponse\x12\x1c\n" +
	"\ttriggered\x18\x01 \x01(\bR\ttriggered\x12!\n" +
	"\fqueue_length\x18\x02 \x01(\x05R\vqueueLength\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x9e\x01\n" +
	"\x14CreateChannelRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\fchannel_type\x18\x03 \x01(\tR\vchannelType\x122\n" +
	"\x06config\x18\x04 \x01(\v2\x1a.attestation.ChannelConfigR\x06config\"\xa9\x01\n" +
	"\rChannelConfig\x12>\n" +
	"\x1bsettlement_interval_seconds\x18\x01 \x01(\x05R\x19settlementIntervalSeconds\x127\n" +
	"\x18max_events_before_settle\x18\x02 \x01(\x05R\x15maxEventsBeforeSettle\x12\x1f\n" +
	"\vauto_settle\x18\x03 \x01(\bR\n" +
	"autoSettle\"\xe8\x03\n" +
	"\x0fChannelResponse\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12)\n" +
	"\x10current_sequence\x18\x04 \x01(\x03R\x0fcurrentSequence\x12!\n" +
	"\ftotal_events\x18\x05 \x01(\x03R\vtotalEvents\x12%\n" +
	"\x0epending_events\x18\x06 \x01(\x03R\rpendingEvents\x122\n" +
	"\x15last_settled_sequence\x18\a \x01(\x03R\x13lastSettledSequence\x12.\n" +
	"\x13current_merkle_root\x18\b \x01(\tR\x11currentMerkleRoot\x12)\n" +
	"\x10settlement_count\x18\t \x01(\x05R\x0fsettlementCount\x125\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x16.attestation.TimestampR\tcreatedAt\x12H\n" +
	"\x14last_settlement_time\x18\v \x01(\v2\x16.attestation.TimestampR\x12lastSettlementTime\"\xf9\x01\n" +
	"\x13ChannelEventRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x19\n" +
	"\bevent_id\x18\x03 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x04 \x01(\tR\teventType\x12\x1b\n" +
	"\tdata_hash\x18\x05 \x01(\tR\bdataHash\x121\n" +
	"\bmetadata\x18\x06 \x01(\v2\x15.attestation.MetadataR\bmetadata\x12\x1c\n" +
	"\tsignature\x18\a \x01(\tR\tsignature\"\xca\x01\n" +
	"\x14ChannelEventResponse\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x03R\bsequence\x12\x1d\n" +
	"\n" +
	"event_hash\x18\x03 \x01(\tR\teventHash\x12\x1f\n" +
	"\vmerkle_root\x18\x04 \x01(\tR\n" +
	"merkleRoot\x12#\n" +
	"\rshould_settle\x18\x05 \x01(\bR\fshouldSettle\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\"R\n" +
	"\x14ChannelStatusRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\"R\n" +
	"\x14SettleChannelRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\"\xb8\x02\n" +
	"\x12SettlementResponse\x12#\n" +
	"\rsettlement_id\x18\x01 \x01(\tR\fsettlementId\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\tR\tchannelId\x12\x1f\n" +
	"\vmerkle_root\x18\x03 \x01(\tR\n" +
	"merkleRoot\x12\x1f\n" +
	"\vevent_count\x18\x04 \x01(\x03R\n" +
	"eventCount\x12%\n" +
	"\x0estart_sequence\x18\x05 \x01(\x03R\rstartSequence\x12!\n" +
	"\fend_sequence\x18\x06 \x01(\x03R\vendSequence\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x17\n" +
	"\atx_hash\x18\b \x01(\tR\x06txHash\x12!\n" +
	"\fblock_number\x18\t \x01(\x03R\vblockNumber\"t\n" +
	"\x13CloseChannelRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12!\n" +
	"\fsettle_first\x18\x03 \x01(\bR\vsettleFirst\"/\n" +
	"\x10EndpointsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\"\xa2\x01\n" +
	"\x11EndpointsResponse\x123\n" +
	"\tendpoints\x18\x01 \x03(\v2\x15.attestation.EndpointR\tendpoints\x127\n" +
	"\x17recommended_connections\x18\x02 \x01(\x05R\x16recommendedConnections\x12\x1f\n" +
	"\vttl_seconds\x18\x03 \x01(\x05R\n" +
	"ttlSeconds\"\x90\x01\n" +
	"\bEndpoint\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x17\n" +
	"\ause_tls\x18\x02 \x01(\bR\x06useTls\x12\x16\n" +
	"\x06weight\x18\x03 \x01(\x05R\x06weight\x12\x16\n" +
	"\x06region\x18\x04 \x01(\tR\x06region\x12!\n" +
	"\fcurrent_load\x18\x05 \x01(\x05R\vcurrentLoad\"\x14\n" +
	"\x12ClusterInfoRequest\"\xd1\x01\n" +
	"\x13ClusterInfoResponse\x12\x1f\n" +
	"\vtotal_nodes\x18\x01 \x01(\x05R\n" +
	"totalNodes\x12#\n" +
	"\rhealthy_nodes\x18\x02 \x01(\x05R\fhealthyNodes\x12*\n" +
	"\x11events_per_second\x18\x03 \x01(\x03R\x0feventsPerSecond\x12\x1f\n" +
	"\vqueue_depth\x18\x04 \x01(\x03R\n" +
	"queueDepth\x12'\n" +
	"\x0fcluster_version\x18\x05 \x01(\tR\x0eclusterVersion2\x93\x03\n" +
	"\fEventService\x12I\n" +
	"\fStreamEvents\x12\x19.attestation.EventRequest\x1a\x1a.attestation.EventResponse(\x010\x01\x12D\n" +
	"\vSubmitEvent\x12\x19.attestation.EventRequest\x1a\x1a.attestation.EventResponse\x12N\n" +
	"\vSubmitBatch\x12\x1e.attestation.BatchEventRequest\x1a\x1f.attestation.BatchEventResponse\x12S\n" +
	"\x0eGetEventStatus\x12\x1f.attestation.EventStatusRequest\x1a .attestation.EventStatusResponse\x12M\n" +
	"\n" +
	"ForceBatch\x12\x1e.attestation.ForceBatchRequest\x1a\x1f.attestation.ForceBatchResponse2\xbd\x03\n" +
	"\x13StateChannelService\x12P\n" +
	"\rCreateChannel\x12!.attestation.CreateChannelRequest\x1a\x1c.attestation.ChannelResponse\x12Z\n" +
	"\x0fStreamToChannel\x12 .attestation.ChannelEventRequest\x1a!.attestation.ChannelEventResponse(\x010\x01\x12S\n" +
	"\x10GetChannelStatus\x12!.attestation.ChannelStatusRequest\x1a\x1c.attestation.ChannelResponse\x12S\n" +
	"\rSettleChannel\x12!.attestation.SettleChannelRequest\x1a\x1f.attestation.SettlementResponse\x12N\n" +
	"\fCloseChannel\x12 .attestation.CloseChannelRequest\x1a\x1c.attestation.ChannelResponse2\xb6\x01\n" +
	"\x10DiscoveryService\x12M\n" +
	"\fGetEndpoints\x12\x1d.attestation.EndpointsRequest\x1a\x1e.attestation.EndpointsResponse\x12S\n" +
	"\x0eGetClusterInfo\x12\x1f.attestation.ClusterInfoRequest\x1a .attestation.ClusterInfoResponseB5Z3github.com/ProofChainZA/proofchain-go/proofchain/pbb\x06proto3"

var (
	file_attestation_proto_rawDescOnce sync.Once
	file_attestation_proto_rawDescData []byte
)

func file_attestation_proto_rawDescGZIP() []byte {
	file_attestation_proto_rawDescOnce.Do(func() {
		file_attestation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_attestation_proto_rawDesc), len(file_attestation_proto_rawDesc)))
	})
	return file_attestation_proto_rawDescData
}

var file_attestation_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_attestation_proto_goTypes = []any{
	(*Metadata)(nil),             // 0: attestation.Metadata
	(*Timestamp)(nil),            // 1: attestation.Timestamp
	(*EventRequest)(nil),         // 2: attestation.EventRequest
	(*EventResponse)(nil),        // 3: attestation.EventResponse
	(*BatchEventRequest)(nil),    // 4: attestation.BatchEventRequest
	(*BatchEventResponse)(nil),   // 5: attestation.BatchEventResponse
	(*EventStatusRequest)(nil),   // 6: attestation.EventStatusRequest
	(*EventStatusResponse)(nil),  // 7: attestation.EventStatusResponse
	(*ForceBatchRequest)(nil),    // 8: attestation.ForceBatchRequest
	(*ForceBatchResponse)(nil),   // 9: attestation.ForceBatchResponse
	(*CreateChannelRequest)(nil), // 10: attestation.CreateChannelRequest
	(*ChannelConfig)(nil),        // 11: attestation.ChannelConfig
	(*ChannelResponse)(nil),      // 12: attestation.ChannelResponse
	(*ChannelEventRequest)(nil),  // 13: attestation.ChannelEventRequest
	(*ChannelEventResponse)(nil), // 14: attestation.ChannelEventResponse
	(*ChannelStatusRequest)(nil), // 15: attestation.ChannelStatusRequest
	(*SettleChannelRequest)(nil), // 16: attestation.SettleChannelRequest
	(*SettlementResponse)(nil),   // 17: attestation.SettlementResponse
	(*CloseChannelRequest)(nil),  // 18: attestation.CloseChannelRequest
	(*EndpointsRequest)(nil),     // 19: attestation.EndpointsRequest
	(*EndpointsResponse)(nil),    // 20: attestation.EndpointsResponse
	(*Endpoint)(nil),             // 21: attestation.Endpoint
	(*ClusterInfoRequest)(nil),   // 22: attestation.ClusterInfoRequest
	(*ClusterInfoResponse)(nil),  // 23: attestation.ClusterInfoResponse
	nil,                          // 24: attestation.Metadata.FieldsEntry
}
var file_attestation_proto_depIdxs = []int32{
	24, // 0: attestation.Metadata.fields:type_name -> attestation.Metadata.FieldsEntry
	0,  // 1: attestation.EventRequest.metadata:type_name -> attestation.Metadata
	1,  // 2: attestation.EventRequest.timestamp:type_name -> attestation.Timestamp
	2,  // 3: attestation.BatchEventRequest.events:type_name -> attestation.EventRequest
	3,  // 4: attestation.BatchEventResponse.responses:type_name -> attestation.EventResponse
	11, // 5: attestation.CreateChannelRequest.config:type_name -> attestation.ChannelConfig
	1,  // 6: attestation.ChannelResponse.created_at:type_name -> attestation.Timestamp
	1,  // 7: attestation.ChannelResponse.last_settlement_time:type_name -> attestation.Timestamp
	0,  // 8: attestation.ChannelEventRequest.metadata:type_name -> attestation.Metadata
	21, // 9: attestation.EndpointsResponse.endpoints:type_name -> attestation.Endpoint
	2,  // 10: attestation.EventService.StreamEvents:input_type -> attestation.EventRequest
	2,  // 11: attestation.EventService.SubmitEvent:input_type -> attestation.EventRequest
	4,  // 12: attestation.EventService.SubmitBatch:input_type -> attestation.BatchEventRequest
	6,  // 13: attestation.EventService.GetEventStatus:input_type -> attestation.EventStatusRequest
	8,  // 14: attestation.EventService.ForceBatch:input_type -> attestation.ForceBatchRequest
	10, // 15: attestation.StateChannelService.CreateChannel:input_type -> attestation.CreateChannelRequest
	13, // 16: attestation.StateChannelService.StreamToChannel:input_type -> attestation.ChannelEventRequest
	15, // 17: attestation.StateChannelService.GetChannelStatus:input_type -> attestation.ChannelStatusRequest
	16, // 18: attestation.StateChannelService.SettleChannel:input_type -> attestation.SettleChannelRequest
	18, // 19: attestation.StateChannelService.CloseChannel:input_type -> attestation.CloseChannelRequest
	19, // 20: attestation.DiscoveryService.GetEndpoints:input_type -> attestation.EndpointsRequest
	22, // 21: attestation.DiscoveryService.GetClusterInfo:input_type -> attestation.ClusterInfoRequest
	3,  // 22: attestation.EventService.StreamEvents:output_type -> attestation.EventResponse
	3,  // 23: attestation.EventService.SubmitEvent:output_type -> attestation.EventResponse
	5,  // 24: attestation.EventService.SubmitBatch:output_type -> attestation.BatchEventResponse
	7,  // 25: attestation.EventService.GetEventStatus:output_type -> attestation.EventStatusResponse
	9,  // 26: attestation.EventService.ForceBatch:output_type -> attestation.ForceBatchResponse
	12, // 27: attestation.StateChannelService.CreateChannel:output_type -> attestation.ChannelResponse
	14, // 28: attestation.StateChannelService.StreamToChannel:output_type -> attestation.ChannelEventResponse
	12, // 29: attestation.StateChannelService.GetChannelStatus:output_type -> attestation.ChannelResponse
	17, // 30: attestation.StateChannelService.SettleChannel:output_type -> attestation.SettlementResponse
	12, // 31: attestation.StateChannelService.CloseChannel:output_type -> attestation.ChannelResponse
	20, // 32: attestation.DiscoveryService.GetEndpoints:output_type -> attestation.EndpointsResponse
	23, // 33: attestation.DiscoveryService.GetClusterInfo:output_type -> attestation.ClusterInfoResponse
	22, // [22:34] is the sub-list for method output_type
	10, // [10:22] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_attestation_proto_init() }
func file_attestation_proto_init() {
	if File_attestation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_attestation_proto_rawDesc), len(file_attestation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_attestation_proto_goTypes,
		DependencyIndexes: file_attestation_proto_depIdxs,
		MessageInfos:      file_attestation_proto_msgTypes,
	}.Build()
	File_attestation_proto = out.File
	file_attestation_proto_goTypes = nil
	file_attestation_proto_depIdxs = nil
}
